--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: fn_auditoria_generica(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.fn_auditoria_generica() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_id_usuario  bigint;
    v_id_registro bigint;
    v_pk_column   text;
    v_row         jsonb;
BEGIN
    BEGIN
        v_id_usuario := NULLIF(current_setting('app.id_usuario', true), '')::bigint;
    EXCEPTION WHEN OTHERS THEN
        v_id_usuario := NULL;
    END;

    IF TG_NARGS > 0 THEN
        v_pk_column := TG_ARGV[0];
    END IF;

    IF TG_OP = 'DELETE' THEN
        v_row := to_jsonb(OLD);
    ELSE
        v_row := to_jsonb(NEW);
    END IF;

    IF v_pk_column IS NOT NULL THEN
        BEGIN
            v_id_registro := (v_row ->> v_pk_column)::bigint;
        EXCEPTION WHEN OTHERS THEN
            v_id_registro := NULL;
        END;
    END IF;

    IF TG_OP = 'DELETE' THEN
        INSERT INTO public.auditoria (modulo, accion, id_registro, id_usuario, datos_anteriores, detalle)
        VALUES (TG_TABLE_NAME, 'DELETE', v_id_registro, v_id_usuario, to_jsonb(OLD),
                'Eliminación de registro en ' || TG_TABLE_NAME);
        RETURN OLD;

    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO public.auditoria (modulo, accion, id_registro, id_usuario, datos_anteriores, datos_nuevos, detalle)
        VALUES (TG_TABLE_NAME, 'UPDATE', v_id_registro, v_id_usuario, to_jsonb(OLD), to_jsonb(NEW),
                'Actualización de registro en ' || TG_TABLE_NAME);
        RETURN NEW;

    ELSIF TG_OP = 'INSERT' THEN
        INSERT INTO public.auditoria (modulo, accion, id_registro, id_usuario, datos_nuevos, detalle)
        VALUES (TG_TABLE_NAME, 'INSERT', v_id_registro, v_id_usuario, to_jsonb(NEW),
                'Creación de registro en ' || TG_TABLE_NAME);
        RETURN NEW;
    END IF;

    RETURN NULL;
END;
$$;


ALTER FUNCTION public.fn_auditoria_generica() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accion_permiso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accion_permiso (
    id_accion_permiso bigint NOT NULL,
    nombre character varying(60) NOT NULL
);


ALTER TABLE public.accion_permiso OWNER TO postgres;

--
-- Name: accion_permiso_id_accion_permiso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accion_permiso ALTER COLUMN id_accion_permiso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accion_permiso_id_accion_permiso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actividad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividad (
    id_actividad bigint NOT NULL,
    ambito character varying(20) NOT NULL,
    nombre character varying(60) NOT NULL,
    descripcion character varying(200),
    estado smallint DEFAULT 1 NOT NULL
);


ALTER TABLE public.actividad OWNER TO postgres;

--
-- Name: actividad_id_actividad_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actividad ALTER COLUMN id_actividad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividad_id_actividad_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actividad_terreno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividad_terreno (
    id_actividad_terreno bigint NOT NULL,
    id_seguimiento_terreno bigint NOT NULL,
    id_actividad bigint NOT NULL
);


ALTER TABLE public.actividad_terreno OWNER TO postgres;

--
-- Name: actividad_terreno_id_actividad_terreno_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actividad_terreno ALTER COLUMN id_actividad_terreno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividad_terreno_id_actividad_terreno_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actividad_zoocriadero; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actividad_zoocriadero (
    id_actividad_zoocriadero bigint NOT NULL,
    id_seguimiento bigint NOT NULL,
    id_actividad bigint NOT NULL
);


ALTER TABLE public.actividad_zoocriadero OWNER TO postgres;

--
-- Name: actividad_zoocriadero_id_actividad_zoocriadero_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actividad_zoocriadero ALTER COLUMN id_actividad_zoocriadero ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actividad_zoocriadero_id_actividad_zoocriadero_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auditoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auditoria (
    id_auditoria bigint NOT NULL,
    modulo character varying(60) NOT NULL,
    accion character varying(20) NOT NULL,
    id_registro bigint,
    id_usuario bigint,
    datos_anteriores jsonb,
    datos_nuevos jsonb,
    detalle character varying(300),
    fecha_hora timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.auditoria OWNER TO postgres;

--
-- Name: auditoria_id_auditoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auditoria ALTER COLUMN id_auditoria ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.auditoria_id_auditoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: barrio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.barrio (
    id_barrio bigint NOT NULL,
    id_comuna bigint,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.barrio OWNER TO postgres;

--
-- Name: barrio_id_barrio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.barrio ALTER COLUMN id_barrio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barrio_id_barrio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ciudad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ciudad (
    id_ciudad bigint NOT NULL,
    id_comuna bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.ciudad OWNER TO postgres;

--
-- Name: ciudad_id_ciudad_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ciudad ALTER COLUMN id_ciudad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ciudad_id_ciudad_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comuna; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comuna (
    id_comuna bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.comuna OWNER TO postgres;

--
-- Name: comuna_id_comuna_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comuna ALTER COLUMN id_comuna ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comuna_id_comuna_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: copia_seguridad_historial; Type: TABLE; Schema: public; Owner: postgres
--
-- Usada por Model/CopiaSeguridad/CopiaSeguridadModel.php
-- (registrarOperacion/historial/ultimoBackupExitoso). No existía en
-- ningún respaldo, aunque el módulo de Copia de Seguridad ya la usa
-- activamente para guardar el historial de cada backup/restauración
-- (el archivo .sql en sí vive en disco, no aquí).
--

CREATE TABLE public.copia_seguridad_historial (
    id_historial bigint NOT NULL,
    fecha_hora timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tipo_operacion character varying(30) NOT NULL,
    nombre_archivo character varying(200),
    id_usuario bigint,
    usuario_nombre character varying(160),
    estado character varying(20) NOT NULL,
    detalle character varying(300)
);


ALTER TABLE public.copia_seguridad_historial OWNER TO postgres;

--
-- Name: copia_seguridad_historial_id_historial_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.copia_seguridad_historial ALTER COLUMN id_historial ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.copia_seguridad_historial_id_historial_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departamento (
    id_departamento bigint NOT NULL,
    id_ciudad bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.departamento OWNER TO postgres;

--
-- Name: departamento_id_departamento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departamento ALTER COLUMN id_departamento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departamento_id_departamento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deposito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deposito (
    id_deposito bigint NOT NULL,
    id_tipo_deposito bigint NOT NULL,
    id_sitio bigint NOT NULL,
    descripcion character varying(200),
    estado smallint DEFAULT 1 NOT NULL
);


ALTER TABLE public.deposito OWNER TO postgres;

--
-- Name: deposito_id_deposito_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deposito ALTER COLUMN id_deposito ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposito_id_deposito_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: direccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.direccion (
    id_direccion bigint NOT NULL,
    id_departamento bigint NOT NULL,
    id_comuna bigint NOT NULL,
    id_ciudad bigint NOT NULL,
    id_barrio bigint NOT NULL,
    direccion character varying(200) NOT NULL,
    id_nomenclatura bigint NOT NULL,
    latitud numeric(10,8),
    longitud numeric(11,8)
);


ALTER TABLE public.direccion OWNER TO postgres;

--
-- Name: direccion_id_direccion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.direccion ALTER COLUMN id_direccion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.direccion_id_direccion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modulo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.modulo (
    id_modulo bigint NOT NULL,
    nombre character varying(60) NOT NULL,
    descripcion character varying(200)
);


ALTER TABLE public.modulo OWNER TO postgres;

--
-- Name: modulo_accion_permitida; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.modulo_accion_permitida (
    id_modulo bigint NOT NULL,
    id_accion_permiso bigint NOT NULL
);


ALTER TABLE public.modulo_accion_permitida OWNER TO postgres;

--
-- Name: modulo_id_modulo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.modulo ALTER COLUMN id_modulo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modulo_id_modulo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nomenclatura; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nomenclatura (
    id_nomenclatura bigint NOT NULL,
    nomenclatura character varying(100) NOT NULL
);


ALTER TABLE public.nomenclatura OWNER TO postgres;

--
-- Name: nomenclatura_id_nomenclatura_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.nomenclatura ALTER COLUMN id_nomenclatura ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nomenclatura_id_nomenclatura_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id_rol bigint NOT NULL,
    nombre_rol character varying(50) NOT NULL,
    descripcion character varying(200),
    estado smallint DEFAULT 1 NOT NULL
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- Name: rol_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rol ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol_permiso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol_permiso (
    id_rol bigint NOT NULL,
    id_modulo bigint NOT NULL,
    id_accion_permiso bigint NOT NULL
);


ALTER TABLE public.rol_permiso OWNER TO postgres;

--
-- Name: seguimiento_terreno; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seguimiento_terreno (
    id_seguimiento_terreno bigint NOT NULL,
    id_sitio bigint NOT NULL,
    id_usuario bigint NOT NULL,
    fecha date NOT NULL,
    estado smallint DEFAULT 1 NOT NULL
);


ALTER TABLE public.seguimiento_terreno OWNER TO postgres;

--
-- Name: seguimiento_terreno_id_seguimiento_terreno_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.seguimiento_terreno ALTER COLUMN id_seguimiento_terreno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seguimiento_terreno_id_seguimiento_terreno_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seguimiento_zoocriadero; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seguimiento_zoocriadero (
    id_seguimiento bigint NOT NULL,
    id_zoocriadero bigint NOT NULL,
    id_tanque bigint NOT NULL,
    id_usuario bigint NOT NULL,
    fecha date NOT NULL,
    ph numeric(4,2),
    temperatura numeric(4,2),
    numero_sembrados integer DEFAULT 0,
    numero_nacidos integer DEFAULT 0,
    numero_nacidos_hembra integer DEFAULT 0 NOT NULL,
    numero_nacidos_macho integer DEFAULT 0 NOT NULL,
    numero_muertos integer DEFAULT 0,
    numero_muertos_hembra integer DEFAULT 0 NOT NULL,
    numero_muertos_macho integer DEFAULT 0 NOT NULL,
    observaciones character varying(300),
    estado smallint DEFAULT 1 NOT NULL
);


ALTER TABLE public.seguimiento_zoocriadero OWNER TO postgres;

--
-- Name: seguimiento_zoocriadero_id_seguimiento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.seguimiento_zoocriadero ALTER COLUMN id_seguimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seguimiento_zoocriadero_id_seguimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sitio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sitio (
    id_sitio bigint NOT NULL,
    nombre character varying(100) DEFAULT 'Sitio de campo'::character varying NOT NULL,
    descripcion character varying(200),
    id_direccion bigint NOT NULL,
    estado smallint DEFAULT 1 NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT sitio_creado_en_not_null NOT NULL
);


ALTER TABLE public.sitio OWNER TO postgres;

--
-- Name: sitio_id_sitio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sitio ALTER COLUMN id_sitio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sitio_id_sitio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tanque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tanque (
    id_tanque bigint NOT NULL,
    id_zoocriadero bigint NOT NULL,
    id_tipo_tanque bigint NOT NULL,
    numero_tanque integer NOT NULL,
    estado smallint DEFAULT 1 NOT NULL
);


ALTER TABLE public.tanque OWNER TO postgres;

--
-- Name: tanque_id_tanque_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tanque ALTER COLUMN id_tanque ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tanque_id_tanque_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: territorio_priorizado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.territorio_priorizado (
    id_territorio bigint NOT NULL,
    comuna character varying(60),
    barrio character varying(60),
    sitio character varying(100),
    direccion_sitio character varying(200),
    nombre_lider character varying(120),
    direccion_lider character varying(200),
    telefono_lider character varying(30),
    correo_lider character varying(120),
    clase_liderazgo character varying(80),
    id_funcionario_ecosalud bigint,
    latitud numeric(10,8),
    longitud numeric(11,8),
    fecha_registro date DEFAULT CURRENT_DATE NOT NULL,
    estado smallint DEFAULT 1 NOT NULL
);


ALTER TABLE public.territorio_priorizado OWNER TO postgres;

--
-- Name: territorio_priorizado_id_territorio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.territorio_priorizado ALTER COLUMN id_territorio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.territorio_priorizado_id_territorio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_deposito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_deposito (
    id_tipo_deposito bigint NOT NULL,
    nombre character varying(60) NOT NULL,
    descripcion character varying(200),
    estado smallint DEFAULT 1 NOT NULL
);


ALTER TABLE public.tipo_deposito OWNER TO postgres;

--
-- Name: tipo_deposito_id_tipo_deposito_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_deposito ALTER COLUMN id_tipo_deposito ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_deposito_id_tipo_deposito_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_documento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_documento (
    id_tipodocumento bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.tipo_documento OWNER TO postgres;

--
-- Name: tipo_documento_id_tipodocumento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_documento ALTER COLUMN id_tipodocumento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_documento_id_tipodocumento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_tanque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_tanque (
    id_tipo_tanque bigint NOT NULL,
    nombre character varying(60) NOT NULL,
    descripcion character varying(200),
    estado smallint DEFAULT 1 NOT NULL
);


ALTER TABLE public.tipo_tanque OWNER TO postgres;

--
-- Name: tipo_tanque_id_tipo_tanque_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_tanque ALTER COLUMN id_tipo_tanque ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_tanque_id_tipo_tanque_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario bigint NOT NULL,
    id_tipodocumento bigint NOT NULL,
    id_rol bigint NOT NULL,
    documento character varying(20) NOT NULL,
    nombre character varying(80) NOT NULL,
    apellido character varying(80) NOT NULL,
    correo character varying(120) NOT NULL,
    contrasena character varying(255) NOT NULL,
    intentos_fallidos integer DEFAULT 0 NOT NULL,
    bloqueo_hasta timestamp without time zone,
    token_recuperacion character varying(255) DEFAULT NULL::character varying,
    token_expira timestamp without time zone,
    estado smallint DEFAULT 1 NOT NULL,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vista_auditoria; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vista_auditoria AS
 SELECT a.id_auditoria,
    a.modulo,
    a.accion,
    a.id_registro,
    a.id_usuario,
    COALESCE((((u.nombre)::text || ' '::text) || (u.apellido)::text), 'Desconocido'::text) AS usuario,
    a.detalle,
    a.datos_anteriores,
    a.datos_nuevos,
    a.fecha_hora
   FROM (public.auditoria a
     LEFT JOIN public.usuario u ON ((u.id_usuario = a.id_usuario)))
  ORDER BY a.fecha_hora DESC;


ALTER VIEW public.vista_auditoria OWNER TO postgres;

--
-- Name: zoocriadero; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zoocriadero (
    id_zoocriadero bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    direccion character varying(200) NOT NULL,
    comuna character varying(60),
    barrio character varying(60),
    id_persona_cargo bigint,
    latitud numeric(10,8) NOT NULL,
    longitud numeric(11,8) NOT NULL,
    estado smallint DEFAULT 1 NOT NULL,
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.zoocriadero OWNER TO postgres;

--
-- Name: zoocriadero_id_zoocriadero_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zoocriadero ALTER COLUMN id_zoocriadero ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zoocriadero_id_zoocriadero_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accion_permiso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accion_permiso (id_accion_permiso, nombre) FROM stdin;
1	Ver
2	Crear
3	Editar
4	Inhabilitar
5	Exportar
7	Consultar
\.


--
-- Data for Name: actividad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actividad (id_actividad, ambito, nombre, descripcion, estado) FROM stdin;
2	zoocriadero	Medición Parámetros	Control de PH, Temperatura y Oxígeno	1
5	terreno	Inspección Larvaria	Búsqueda de larvas de Aedes aegypti	1
6	terreno	Siembra de Guppies en Campo	Liberación de peces controladores de larvas	1
7	terreno	Capacitación Comunitaria	Educación sobre control de dengue	1
24	zoocriadero	Limpiar tanque	Limpieza general del tanque y retiro de residuos	1
25	zoocriadero	Contar peces	Conteo de peces vivos, nacidos y muertos	1
26	zoocriadero	Equilibrar pH	Ajuste del pH del agua al rango 6.5 - 7.5	1
27	zoocriadero	Medir temperatura	Medición y ajuste de la temperatura del agua	1
28	zoocriadero	Sembrar alevinos	Siembra de alevinos en el tanque	1
29	zoocriadero	Cosechar peces	Extracción de peces para entrega a la comunidad	1
30	zoocriadero	Alimentar peces	Suministro de alimento concentrado	1
31	zoocriadero	Cambiar agua	Recambio parcial o total del agua	1
32	zoocriadero	Limpiar filtro	Limpieza o cambio del sistema de filtrado	1
33	zoocriadero	Retirar peces muertos	Retiro de la mortalidad encontrada en el tanque	1
34	zoocriadero	Revisar oxigenación	Revisión del sistema de aireación del tanque	1
35	zoocriadero	Clasificar por tallas	Separación de los peces según su tamaño	1
36	zoocriadero	Revisar reproducción	Verificación de hembras grávidas y crías	1
37	zoocriadero	Aplicar tratamiento	Tratamiento sanitario a los peces del tanque	1
38	terreno	Inspección	Inspección de depósitos en vivienda	1
39	terreno	Eliminación	Eliminación de criaderos encontrados	1
40	terreno	Larvicida	Aplicación de larvicida en depósitos útiles	1
41	terreno	Entrega de peces	Entrega de guppys a la comunidad	1
42	terreno	Educación	Jornada de educación sanitaria	1
43	terreno	Lavado	Lavado y cepillado de tanques y albercas	1
44	terreno	Tapado	Tapado de depósitos de agua	1
45	terreno	Seguimiento	Visita de seguimiento a vivienda intervenida	1
46	terreno	Censo de criaderos	Registro de depósitos por vivienda	1
\.


--
-- Data for Name: actividad_terreno; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actividad_terreno (id_actividad_terreno, id_seguimiento_terreno, id_actividad) FROM stdin;
\.


--
-- Data for Name: actividad_zoocriadero; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actividad_zoocriadero (id_actividad_zoocriadero, id_seguimiento, id_actividad) FROM stdin;
1	1	30
\.


--
-- Data for Name: auditoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auditoria (id_auditoria, modulo, accion, id_registro, id_usuario, datos_anteriores, datos_nuevos, detalle, fecha_hora) FROM stdin;
1	usuario	INSERT	4	\N	\N	{"correo": "admin.pruebas@siguppy.com", "estado": 1, "id_rol": 2, "nombre": "Admin", "apellido": "Pruebas", "creado_en": "2026-09-19T21:52:25.932028", "documento": "9999999999", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 4, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Creación de registro en usuario	2026-09-19 21:52:25.932028
2	usuario	UPDATE	4	\N	{"correo": "admin.pruebas@siguppy.com", "estado": 1, "id_rol": 2, "nombre": "Admin", "apellido": "Pruebas", "creado_en": "2026-09-19T21:52:25.932028", "documento": "9999999999", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 4, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "admin.pruebas@siguppy.com", "estado": 1, "id_rol": 2, "nombre": "Admin", "apellido": "Pruebas", "creado_en": "2026-09-19T21:52:25.932028", "documento": "9999999999", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 4, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 1, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-19 22:05:06.967478
3	usuario	INSERT	5	\N	\N	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Creación de registro en usuario	2026-09-19 22:06:06.811595
4	usuario	UPDATE	5	\N	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 1, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-19 22:06:18.655282
5	usuario	UPDATE	5	\N	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 1, "token_recuperacion": null}	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-19 22:06:33.259257
6	usuario	UPDATE	5	\N	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 10:06:35.503415
7	usuario	UPDATE	4	\N	{"correo": "admin.pruebas@siguppy.com", "estado": 1, "id_rol": 2, "nombre": "Admin", "apellido": "Pruebas", "creado_en": "2026-09-19T21:52:25.932028", "documento": "9999999999", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 4, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 1, "token_recuperacion": null}	{"correo": "admin.pruebas@cali.gov.co", "estado": 1, "id_rol": 1, "nombre": "Admin", "apellido": "Pruebas", "creado_en": "2026-09-19T21:52:25.932028", "documento": "9999999999", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 4, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 1, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 10:09:58.246238
8	usuario	UPDATE	5	\N	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 10:10:34.655828
9	rol	INSERT	5	\N	\N	{"estado": 1, "id_rol": 5, "nombre_rol": "terreno", "descripcion": "prueba terreno"}	Creación de registro en rol	2026-09-20 10:11:31.561399
10	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 9, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
11	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 10, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
12	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 12, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
13	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 9, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
14	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 10, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
15	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 12, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
16	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 9, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
17	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 10, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
18	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 12, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
19	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 9, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
20	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 10, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
21	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 12, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
22	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 9, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
23	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 10, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
24	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 5, "id_modulo": 12, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:11:31.561399
25	usuario	UPDATE	4	\N	{"correo": "admin.pruebas@cali.gov.co", "estado": 1, "id_rol": 1, "nombre": "Admin", "apellido": "Pruebas", "creado_en": "2026-09-19T21:52:25.932028", "documento": "9999999999", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 4, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 1, "token_recuperacion": null}	{"correo": "admin.pruebas@cali.gov.co", "estado": 1, "id_rol": 5, "nombre": "Admin", "apellido": "Pruebas", "creado_en": "2026-09-19T21:52:25.932028", "documento": "9999999999", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 4, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 1, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 10:11:42.490766
26	usuario	UPDATE	5	\N	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 10:11:51.895636
27	usuario	UPDATE	5	\N	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 10:12:41.996858
28	usuario	UPDATE	5	\N	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 10:12:54.641642
29	usuario	UPDATE	5	\N	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "idarragalenindavid@gmail.com", "estado": 1, "id_rol": 2, "nombre": "Lenin", "apellido": "Idarraga", "creado_en": "2026-09-19T22:06:06.811595", "documento": "1106516233", "contrasena": "$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK", "id_usuario": 5, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 10:40:37.32346
30	rol	INSERT	6	\N	\N	{"estado": 1, "id_rol": 6, "nombre_rol": "super usuario", "descripcion": "prueba de todos los modulos"}	Creación de registro en rol	2026-09-20 10:43:15.733206
31	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 1, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
32	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 5, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
33	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 7, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
34	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 8, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
35	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 9, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
36	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 10, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
37	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 11, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
38	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 12, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
39	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 13, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
40	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 17, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
41	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 18, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
42	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 19, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
43	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 20, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
44	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 21, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
45	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 22, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
46	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 23, "id_accion_permiso": 1}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
47	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 1, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
48	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 7, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
49	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 8, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
50	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 9, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
51	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 10, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
52	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 11, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
53	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 12, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
54	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 13, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
55	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 19, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
56	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 21, "id_accion_permiso": 2}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
57	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 1, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
58	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 7, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
59	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 8, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
60	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 9, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
61	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 10, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
62	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 11, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
63	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 12, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
64	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 13, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
65	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 19, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
66	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 20, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
67	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 23, "id_accion_permiso": 3}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
68	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 1, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
69	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 7, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
70	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 8, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
71	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 9, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
72	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 10, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
73	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 11, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
74	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 12, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
75	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 13, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
76	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 19, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
77	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 20, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
78	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 22, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
79	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 23, "id_accion_permiso": 4}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
80	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 18, "id_accion_permiso": 5}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
81	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 1, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
82	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 7, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
83	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 8, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
84	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 9, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
85	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 10, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
86	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 11, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
87	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 12, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
88	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 13, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
89	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 19, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
90	rol_permiso	INSERT	\N	\N	\N	{"id_rol": 6, "id_modulo": 20, "id_accion_permiso": 7}	Creación de registro en rol_permiso	2026-09-20 10:43:15.733206
91	usuario	INSERT	6	\N	\N	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Creación de registro en usuario	2026-09-20 10:44:01.475983
92	usuario	UPDATE	6	\N	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 10:44:08.94886
93	usuario	UPDATE	6	\N	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 12:30:38.140698
94	usuario	UPDATE	6	\N	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 13:09:14.441879
95	usuario	UPDATE	6	\N	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 16:16:38.156321
96	usuario	UPDATE	6	\N	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 16:19:18.122917
97	usuario	UPDATE	6	\N	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "lenin@gmail.com", "estado": 1, "id_rol": 6, "nombre": "super usuario", "apellido": "asprilla", "creado_en": "2026-09-20T10:44:01.475983", "documento": "20072004", "contrasena": "$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq", "id_usuario": 6, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 17:17:37.249559
98	usuario	UPDATE	1	\N	{"correo": "juan@gmail.com", "estado": 1, "id_rol": 2, "nombre": "david", "apellido": "gomez", "creado_en": "2026-09-19T21:50:23.26856", "documento": "1109545513", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 1, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "juan@gmail.com", "estado": 0, "id_rol": 2, "nombre": "david", "apellido": "gomez", "creado_en": "2026-09-19T21:50:23.26856", "documento": "1109545513", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 1, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 17:17:48.875907
99	usuario	UPDATE	1	\N	{"correo": "juan@gmail.com", "estado": 0, "id_rol": 2, "nombre": "david", "apellido": "gomez", "creado_en": "2026-09-19T21:50:23.26856", "documento": "1109545513", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 1, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	{"correo": "juan@gmail.com", "estado": 1, "id_rol": 2, "nombre": "david", "apellido": "gomez", "creado_en": "2026-09-19T21:50:23.26856", "documento": "1109545513", "contrasena": "$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S", "id_usuario": 1, "token_expira": null, "bloqueo_hasta": null, "id_tipodocumento": 1, "intentos_fallidos": 0, "token_recuperacion": null}	Actualización de registro en usuario	2026-09-20 17:17:52.121235
\.


--
-- Data for Name: barrio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.barrio (id_barrio, id_comuna, nombre) FROM stdin;
1	1	Terrón Colorado
2	2	Floralia
3	3	El Poblado II
4	4	El Vergel
5	5	El Retiro
6	6	Desepaz
8	2	Ciudadela Floralia
264	11	Guillermo Valencia
\.


--
-- Data for Name: ciudad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ciudad (id_ciudad, id_comuna, nombre) FROM stdin;
1	1	Santiago de Cali
\.


--
-- Data for Name: comuna; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comuna (id_comuna, nombre) FROM stdin;
1	Comuna 1
2	Comuna 6
3	Comuna 13
4	Comuna 14
5	Comuna 15
6	Comuna 21
7	Comuna 2
8	Comuna 18
9	Comuna 7
10	Comuna 5
11	Comuna 4
12	Comuna 16
13	Comuna 8
14	Comuna 11
15	Comuna 3
16	Comuna 9
17	Comuna 22
18	Comuna 17
19	Comuna 19
20	Comuna 10
21	Comuna 20
22	Comuna 12
\.


--
-- Data for Name: departamento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departamento (id_departamento, id_ciudad, nombre) FROM stdin;
1	1	Valle del Cauca
\.


--
-- Data for Name: deposito; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.deposito (id_deposito, id_tipo_deposito, id_sitio, descripcion, estado) FROM stdin;
1	1	1	Sumidero con agua estancada y presencia de larvas	1
2	2	2	Llantas abandonadas en lote baldío	1
3	1	3	Alcantarilla tapada frente a parque	1
4	3	4	Tanque bajo en vivienda sin tapa	1
5	5	5	Charco permanente por fuga de agua	1
6	2	6	Depósito de caucho en taller mecánico	1
\.


--
-- Data for Name: direccion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.direccion (id_direccion, id_departamento, id_comuna, id_ciudad, id_barrio, direccion, id_nomenclatura, latitud, longitud) FROM stdin;
1	1	1	1	1	Calle 12 Oeste # 4-20	1	3.45120000	-76.54890000
2	1	2	1	2	Carrera 4N # 72 C-10	2	3.48910000	-76.49820000
3	1	3	1	3	Calle 72 # 28D-19	1	3.42478140	-76.48252102
4	1	4	1	4	Carrera 32 # 48-12	2	3.41820000	-76.51030000
5	1	5	1	5	Calle 52 # 39-05	1	3.41010000	-76.50520000
6	1	6	1	6	Carrera 23 # 120-45	2	3.43500000	-76.47110000
\.


--
-- Data for Name: modulo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.modulo (id_modulo, nombre, descripcion) FROM stdin;
1	Zoocriaderos	Gestión de tanques, peces y nacimientos
5	Auditoría	Historial de movimientos de usuarios
7	Actividades	CRUD de actividades de terreno
8	Seguimiento de Zoocriadero	Formulario de seguimiento de un zoocriadero
9	Tipo Depósitos	CRUD de tipos de depósito
10	Sitio	Visualización e inspección de sitios
11	Acciones de Zoocriadero	Registro de acciones sobre tanques de un zoocriadero
12	Depósitos	CRUD de depósitos de terreno
13	Territorio priorizado	Gestión de territorios priorizados
17	Copia de seguridad	Respaldo de la base de datos
18	Reportes	Reportes y gráficos del sistema
19	Gestión de Usuarios	Creación de roles y asignación de permisos
20	Tanque Zoocriadero	Gestión de tanques del zoocriadero
21	Roles y Permisos	Gestión de roles y sus permisos por módulo
22	Consultar Roles	Revisar la información detallada de la función de los roles
23	Consultar Usuarios	Consulta de usuarios: ver, editar e inhabilitar
\.


--
-- Data for Name: modulo_accion_permitida; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.modulo_accion_permitida (id_modulo, id_accion_permiso) FROM stdin;
23	1
22	1
21	1
20	1
19	1
18	1
17	1
13	1
12	1
11	1
10	1
9	1
8	1
7	1
5	1
1	1
21	2
19	2
13	2
12	2
11	2
10	2
9	2
8	2
7	2
1	2
23	3
20	3
19	3
13	3
12	3
11	3
10	3
9	3
8	3
7	3
1	3
18	5
20	7
19	7
13	7
12	7
11	7
10	7
9	7
8	7
7	7
1	7
23	4
22	4
20	4
19	4
13	4
12	4
11	4
10	4
9	4
8	4
7	4
1	4
\.


--
-- Data for Name: nomenclatura; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.nomenclatura (id_nomenclatura, nomenclatura) FROM stdin;
1	Calle
2	Carrera
3	Avenida
4	Diagonal
5	Transversal
\.


--
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (id_rol, nombre_rol, descripcion, estado) FROM stdin;
1	Coordinador	Coordina control biológico y ecosalud	1
2	Administrador	Director(a) del Grupo ETV	1
3	Auxiliar	Personal de campo	1
4	Super Administrador	Administra la base de datos y la configuración del sistema	1
5	terreno	prueba terreno	1
6	super usuario	prueba de todos los modulos	1
\.


--
-- Data for Name: rol_permiso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol_permiso (id_rol, id_modulo, id_accion_permiso) FROM stdin;
2	1	1
2	5	1
2	17	1
2	18	1
2	19	1
2	21	1
2	22	1
2	23	1
2	19	2
2	21	2
2	19	3
2	23	3
2	19	4
2	22	4
2	23	4
2	18	5
2	1	7
2	19	7
5	9	1
5	10	1
5	12	1
5	9	2
5	10	2
5	12	2
5	9	3
5	10	3
5	12	3
5	9	4
5	10	4
5	12	4
5	9	7
5	10	7
5	12	7
6	1	1
6	5	1
6	7	1
6	8	1
6	9	1
6	10	1
6	11	1
6	12	1
6	13	1
6	17	1
6	18	1
6	19	1
6	20	1
6	21	1
6	22	1
6	23	1
6	1	2
6	7	2
6	8	2
6	9	2
6	10	2
6	11	2
6	12	2
6	13	2
6	19	2
6	21	2
6	1	3
6	7	3
6	8	3
6	9	3
6	10	3
6	11	3
6	12	3
6	13	3
6	19	3
6	20	3
6	23	3
6	1	4
6	7	4
6	8	4
6	9	4
6	10	4
6	11	4
6	12	4
6	13	4
6	19	4
6	20	4
6	22	4
6	23	4
6	18	5
6	1	7
6	7	7
6	8	7
6	9	7
6	10	7
6	11	7
6	12	7
6	13	7
6	19	7
6	20	7
\.


--
-- Data for Name: seguimiento_terreno; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.seguimiento_terreno (id_seguimiento_terreno, id_sitio, id_usuario, fecha, estado) FROM stdin;
\.


--
-- Data for Name: seguimiento_zoocriadero; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.seguimiento_zoocriadero (id_seguimiento, id_zoocriadero, id_tanque, id_usuario, fecha, ph, temperatura, numero_sembrados, numero_nacidos, numero_nacidos_hembra, numero_nacidos_macho, numero_muertos, numero_muertos_hembra, numero_muertos_macho, observaciones, estado) FROM stdin;
1	1	1	1	2026-09-18	\N	\N	0	0	0	0	0	0	0	Comieron bien	1
\.


--
-- Data for Name: sitio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sitio (id_sitio, nombre, descripcion, id_direccion, estado, fecha) FROM stdin;
1	Sitio Aguablanca 1	\N	1	1	2026-09-19 21:50:23.26856
2	Sitio Llantas N2	\N	2	1	2026-09-19 21:50:23.26856
3	Sitio Alcantarilla N3	\N	3	1	2026-09-19 21:50:23.26856
4	Sitio Tanque N4	\N	4	1	2026-09-19 21:50:23.26856
5	Sitio Charco N5	\N	5	1	2026-09-19 21:50:23.26856
6	Sitio Taller N6	\N	6	1	2026-09-19 21:50:23.26856
\.


--
-- Data for Name: tanque; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tanque (id_tanque, id_zoocriadero, id_tipo_tanque, numero_tanque, estado) FROM stdin;
1	1	10	1	1
2	2	7	1	1
\.


--
-- Data for Name: territorio_priorizado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.territorio_priorizado (id_territorio, comuna, barrio, sitio, direccion_sitio, nombre_lider, direccion_lider, telefono_lider, correo_lider, clase_liderazgo, id_funcionario_ecosalud, latitud, longitud, fecha_registro, estado) FROM stdin;
\.


--
-- Data for Name: tipo_deposito; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_deposito (id_tipo_deposito, nombre, descripcion, estado) FROM stdin;
1	Sumidero / Alcantarilla	Depósito de aguas pluviales en vía pública	1
2	Lanta / Neumático desechado	Depósito artificial a la intemperie	1
3	Tanque de Agua Potable Destapado	Depósito doméstico residencial	1
4	Florero / Maceta	Recipiente doméstico menor	1
5	Charco / Charca estancada	Acumulación natural en vía pública	1
6	Tanque bajo	Tanque de almacenamiento a nivel de piso	1
7	Canaleta	Canaleta obstruida con agua estancada	1
8	Inservible	Recipiente inservible acumulador de agua	1
9	Materas	Materas y platos de materas	1
10	Llanta	Llanta a la intemperie	1
11	Floreros	Floreros de cementerio o de casa	1
12	Bebedero de animal	Recipiente de agua para mascotas	1
13	Tanque elevado	Tanque elevado o de azotea	1
14	Alberca	Alberca o lavadero	1
15	Pozo	Pozo o aljibe descubierto	1
\.


--
-- Data for Name: tipo_documento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_documento (id_tipodocumento, nombre) FROM stdin;
1	Cédula de Ciudadanía
2	Cédula de Extranjería
3	Tarjeta de Identidad
4	Permiso por Protección Temporal
7	Pasaporte
\.


--
-- Data for Name: tipo_tanque; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_tanque (id_tipo_tanque, nombre, descripcion, estado) FROM stdin;
1	Tanque de Concreto 500L	Tanque de cría masiva	1
2	Tanque Plástico 250L	Tanque de aclimatación	1
3	Acuario Observación 80L	Monitoreo de alevines	1
4	Tina Fibra 1000L	Tanque de recolección principal	1
5	Geomembrana	Estanque revestido en geomembrana	1
6	Vidrio	Acuario o pecera de vidrio para cría controlada	1
7	Metálico	Tanque metálico con recubrimiento interno	1
8	Fibra de vidrio	Tanque en fibra de vidrio, resistente a la intemperie	1
9	Plástico	Tanque plástico estándar de 500 a 1000 litros	1
10	Concreto	Estanque en concreto construido en sitio	1
11	Eternit	Tanque tipo eternit reutilizado como estanque	1
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id_usuario, id_tipodocumento, id_rol, documento, nombre, apellido, correo, contrasena, intentos_fallidos, bloqueo_hasta, token_recuperacion, token_expira, estado, creado_en) FROM stdin;
2	1	2	1109545512	Jaider Alexis	Montaño Mondragon	jaidermontano69@gmail.com	$2y$10$SlVYZEBG3aDdWZM4JEr1feLl/RTyEtbVeM3meBB6b6sUbr2jm.v.W	0	\N	\N	\N	1	2026-09-19 21:50:23.26856
3	1	4	1109541234	miguel tovar	sol	tovar232@gmail.com	$2y$10$vkcZBDuN66/hpyx60945p.d2LVcx7Y4yqaXCXYmIxPiCZl8GMWVYO	0	\N	\N	\N	1	2026-09-19 21:50:23.26856
4	1	5	9999999999	Admin	Pruebas	admin.pruebas@cali.gov.co	$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S	1	\N	\N	\N	1	2026-09-19 21:52:25.932028
5	1	2	1106516233	Lenin	Idarraga	idarragalenindavid@gmail.com	$2y$10$kaiVJYeLnsAKN3OOq7VnPeP1YA9eXhR70M.gWVcK8nb.7WqiMobNK	0	\N	\N	\N	1	2026-09-19 22:06:06.811595
6	1	6	20072004	super usuario	asprilla	lenin@gmail.com	$2y$10$KJOuAYh7t9c4IkbE/7DKvuY.pEOXpBlIXM1mwEhKOpIZCuH15X4Mq	0	\N	\N	\N	1	2026-09-20 10:44:01.475983
1	1	2	1109545513	david	gomez	juan@gmail.com	$2y$10$xVZk9DlIgoFE4LfHKwjShuoAS5eEWi9TVLimOklMKTmEvvwfukb2S	0	\N	\N	\N	1	2026-09-19 21:50:23.26856
\.


--
-- Data for Name: zoocriadero; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.zoocriadero (id_zoocriadero, nombre, direccion, comuna, barrio, id_persona_cargo, latitud, longitud, estado, creado_en) FROM stdin;
1	Zoocriadero Aguablanca	Cra 31 # 22-71	Comuna 6	Ciudadela Floralia	\N	3.49529440	-76.49458530	1	2026-09-19 21:50:23.26856
2	Zoocriadero CDTI	Cra 31 # 22-7123	Comuna 4	Guillermo Valencia	\N	3.49529440	-76.49458530	1	2026-09-19 21:50:23.26856
\.


--
-- Name: accion_permiso_id_accion_permiso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accion_permiso_id_accion_permiso_seq', 7, true);


--
-- Name: actividad_id_actividad_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actividad_id_actividad_seq', 46, true);


--
-- Name: actividad_terreno_id_actividad_terreno_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actividad_terreno_id_actividad_terreno_seq', 1, false);


--
-- Name: actividad_zoocriadero_id_actividad_zoocriadero_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actividad_zoocriadero_id_actividad_zoocriadero_seq', 1, false);


--
-- Name: auditoria_id_auditoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auditoria_id_auditoria_seq', 99, true);


--
-- Name: barrio_id_barrio_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.barrio_id_barrio_seq', 264, true);


--
-- Name: ciudad_id_ciudad_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ciudad_id_ciudad_seq', 1, true);


--
-- Name: comuna_id_comuna_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comuna_id_comuna_seq', 22, true);


--
-- Name: departamento_id_departamento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departamento_id_departamento_seq', 1, true);


--
-- Name: deposito_id_deposito_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.deposito_id_deposito_seq', 6, true);


--
-- Name: direccion_id_direccion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.direccion_id_direccion_seq', 6, true);


--
-- Name: modulo_id_modulo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.modulo_id_modulo_seq', 23, true);


--
-- Name: nomenclatura_id_nomenclatura_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.nomenclatura_id_nomenclatura_seq', 5, true);


--
-- Name: rol_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_id_rol_seq', 6, true);


--
-- Name: seguimiento_terreno_id_seguimiento_terreno_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seguimiento_terreno_id_seguimiento_terreno_seq', 1, false);


--
-- Name: seguimiento_zoocriadero_id_seguimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seguimiento_zoocriadero_id_seguimiento_seq', 1, true);


--
-- Name: sitio_id_sitio_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sitio_id_sitio_seq', 6, true);


--
-- Name: tanque_id_tanque_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tanque_id_tanque_seq', 2, true);


--
-- Name: territorio_priorizado_id_territorio_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.territorio_priorizado_id_territorio_seq', 1, false);


--
-- Name: tipo_deposito_id_tipo_deposito_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_deposito_id_tipo_deposito_seq', 15, true);


--
-- Name: tipo_documento_id_tipodocumento_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_documento_id_tipodocumento_seq', 7, true);


--
-- Name: tipo_tanque_id_tipo_tanque_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_tanque_id_tipo_tanque_seq', 11, true);


--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 6, true);


--
-- Name: zoocriadero_id_zoocriadero_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zoocriadero_id_zoocriadero_seq', 2, true);


--
-- Name: accion_permiso accion_permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accion_permiso
    ADD CONSTRAINT accion_permiso_pkey PRIMARY KEY (id_accion_permiso);


--
-- Name: actividad actividad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad
    ADD CONSTRAINT actividad_pkey PRIMARY KEY (id_actividad);


--
-- Name: actividad_terreno actividad_terreno_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad_terreno
    ADD CONSTRAINT actividad_terreno_pkey PRIMARY KEY (id_actividad_terreno);


--
-- Name: actividad_zoocriadero actividad_zoocriadero_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad_zoocriadero
    ADD CONSTRAINT actividad_zoocriadero_pkey PRIMARY KEY (id_actividad_zoocriadero);


--
-- Name: auditoria auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id_auditoria);


--
-- Name: barrio barrio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barrio
    ADD CONSTRAINT barrio_pkey PRIMARY KEY (id_barrio);


--
-- Name: ciudad ciudad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ciudad
    ADD CONSTRAINT ciudad_pkey PRIMARY KEY (id_ciudad);


--
-- Name: comuna comuna_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comuna
    ADD CONSTRAINT comuna_pkey PRIMARY KEY (id_comuna);


--
-- Name: copia_seguridad_historial copia_seguridad_historial_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.copia_seguridad_historial
    ADD CONSTRAINT copia_seguridad_historial_pkey PRIMARY KEY (id_historial);


--
-- Name: departamento departamento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamento
    ADD CONSTRAINT departamento_pkey PRIMARY KEY (id_departamento);


--
-- Name: deposito deposito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposito
    ADD CONSTRAINT deposito_pkey PRIMARY KEY (id_deposito);


--
-- Name: direccion direccion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_pkey PRIMARY KEY (id_direccion);


--
-- Name: modulo_accion_permitida modulo_accion_permitida_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modulo_accion_permitida
    ADD CONSTRAINT modulo_accion_permitida_pkey PRIMARY KEY (id_modulo, id_accion_permiso);


--
-- Name: modulo modulo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modulo
    ADD CONSTRAINT modulo_pkey PRIMARY KEY (id_modulo);


--
-- Name: nomenclatura nomenclatura_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nomenclatura
    ADD CONSTRAINT nomenclatura_pkey PRIMARY KEY (id_nomenclatura);


--
-- Name: rol_permiso rol_permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT rol_permiso_pkey PRIMARY KEY (id_rol, id_modulo, id_accion_permiso);


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id_rol);


--
-- Name: seguimiento_terreno seguimiento_terreno_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT seguimiento_terreno_pkey PRIMARY KEY (id_seguimiento_terreno);


--
-- Name: seguimiento_zoocriadero seguimiento_zoocriadero_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoocriadero
    ADD CONSTRAINT seguimiento_zoocriadero_pkey PRIMARY KEY (id_seguimiento);


--
-- Name: sitio sitio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sitio
    ADD CONSTRAINT sitio_pkey PRIMARY KEY (id_sitio);


--
-- Name: tanque tanque_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tanque
    ADD CONSTRAINT tanque_pkey PRIMARY KEY (id_tanque);


--
-- Name: territorio_priorizado territorio_priorizado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territorio_priorizado
    ADD CONSTRAINT territorio_priorizado_pkey PRIMARY KEY (id_territorio);


--
-- Name: tipo_deposito tipo_deposito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_deposito
    ADD CONSTRAINT tipo_deposito_pkey PRIMARY KEY (id_tipo_deposito);


--
-- Name: tipo_documento tipo_documento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_documento
    ADD CONSTRAINT tipo_documento_pkey PRIMARY KEY (id_tipodocumento);


--
-- Name: tipo_tanque tipo_tanque_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_tanque
    ADD CONSTRAINT tipo_tanque_pkey PRIMARY KEY (id_tipo_tanque);


--
-- Name: usuario usuario_correo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_correo_key UNIQUE (correo);


--
-- Name: usuario usuario_documento_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_documento_key UNIQUE (documento);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- Name: zoocriadero zoocriadero_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoocriadero
    ADD CONSTRAINT zoocriadero_pkey PRIMARY KEY (id_zoocriadero);


--
-- Name: idx_auditoria_accion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_auditoria_accion ON public.auditoria USING btree (accion);


--
-- Name: idx_auditoria_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_auditoria_fecha ON public.auditoria USING btree (fecha_hora);


--
-- Name: idx_auditoria_modulo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_auditoria_modulo ON public.auditoria USING btree (modulo);


--
-- Name: idx_auditoria_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_auditoria_usuario ON public.auditoria USING btree (id_usuario);


--
-- Name: uq_tipo_documento_nombre_ci; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_tipo_documento_nombre_ci ON public.tipo_documento USING btree (lower((nombre)::text));


--
-- Name: actividad_terreno trg_auditoria_actividad_terreno; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_actividad_terreno AFTER INSERT OR DELETE OR UPDATE ON public.actividad_terreno FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_actividad_terreno');


--
-- Name: actividad_zoocriadero trg_auditoria_actividad_zoocriadero; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_actividad_zoocriadero AFTER INSERT OR DELETE OR UPDATE ON public.actividad_zoocriadero FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_actividad_zoocriadero');


--
-- Name: deposito trg_auditoria_deposito; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_deposito AFTER INSERT OR DELETE OR UPDATE ON public.deposito FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_deposito');


--
-- Name: modulo_accion_permitida trg_auditoria_modulo_accion_permitida; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_modulo_accion_permitida AFTER INSERT OR DELETE OR UPDATE ON public.modulo_accion_permitida FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica();


--
-- Name: rol trg_auditoria_rol; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_rol AFTER INSERT OR DELETE OR UPDATE ON public.rol FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_rol');


--
-- Name: rol_permiso trg_auditoria_rol_permiso; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_rol_permiso AFTER INSERT OR DELETE OR UPDATE ON public.rol_permiso FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica();


--
-- Name: seguimiento_terreno trg_auditoria_seguimiento_terreno; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_seguimiento_terreno AFTER INSERT OR DELETE OR UPDATE ON public.seguimiento_terreno FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_seguimiento_terreno');


--
-- Name: seguimiento_zoocriadero trg_auditoria_seguimiento_zoocriadero; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_seguimiento_zoocriadero AFTER INSERT OR DELETE OR UPDATE ON public.seguimiento_zoocriadero FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_seguimiento');


--
-- Name: sitio trg_auditoria_sitio; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_sitio AFTER INSERT OR DELETE OR UPDATE ON public.sitio FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_sitio');


--
-- Name: tanque trg_auditoria_tanque; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_tanque AFTER INSERT OR DELETE OR UPDATE ON public.tanque FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_tanque');


--
-- Name: territorio_priorizado trg_auditoria_territorio_priorizado; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_territorio_priorizado AFTER INSERT OR DELETE OR UPDATE ON public.territorio_priorizado FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_territorio');


--
-- Name: usuario trg_auditoria_usuario; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_usuario AFTER INSERT OR DELETE OR UPDATE ON public.usuario FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_usuario');


--
-- Name: zoocriadero trg_auditoria_zoocriadero; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_auditoria_zoocriadero AFTER INSERT OR DELETE OR UPDATE ON public.zoocriadero FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria_generica('id_zoocriadero');


--
-- Name: actividad_terreno actividad_terreno_id_actividad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad_terreno
    ADD CONSTRAINT actividad_terreno_id_actividad_fkey FOREIGN KEY (id_actividad) REFERENCES public.actividad(id_actividad);


--
-- Name: actividad_terreno actividad_terreno_id_seguimiento_terreno_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad_terreno
    ADD CONSTRAINT actividad_terreno_id_seguimiento_terreno_fkey FOREIGN KEY (id_seguimiento_terreno) REFERENCES public.seguimiento_terreno(id_seguimiento_terreno);


--
-- Name: actividad_zoocriadero actividad_zoocriadero_id_actividad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad_zoocriadero
    ADD CONSTRAINT actividad_zoocriadero_id_actividad_fkey FOREIGN KEY (id_actividad) REFERENCES public.actividad(id_actividad);


--
-- Name: actividad_zoocriadero actividad_zoocriadero_id_seguimiento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actividad_zoocriadero
    ADD CONSTRAINT actividad_zoocriadero_id_seguimiento_fkey FOREIGN KEY (id_seguimiento) REFERENCES public.seguimiento_zoocriadero(id_seguimiento);


--
-- Name: auditoria auditoria_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- Name: barrio barrio_id_comuna_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barrio
    ADD CONSTRAINT barrio_id_comuna_fkey FOREIGN KEY (id_comuna) REFERENCES public.comuna(id_comuna);


--
-- Name: ciudad ciudad_id_comuna_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ciudad
    ADD CONSTRAINT ciudad_id_comuna_fkey FOREIGN KEY (id_comuna) REFERENCES public.comuna(id_comuna);


--
-- Name: departamento departamento_id_ciudad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamento
    ADD CONSTRAINT departamento_id_ciudad_fkey FOREIGN KEY (id_ciudad) REFERENCES public.ciudad(id_ciudad);


--
-- Name: deposito deposito_id_sitio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposito
    ADD CONSTRAINT deposito_id_sitio_fkey FOREIGN KEY (id_sitio) REFERENCES public.sitio(id_sitio);


--
-- Name: deposito deposito_id_tipo_deposito_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deposito
    ADD CONSTRAINT deposito_id_tipo_deposito_fkey FOREIGN KEY (id_tipo_deposito) REFERENCES public.tipo_deposito(id_tipo_deposito);


--
-- Name: direccion direccion_id_barrio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_id_barrio_fkey FOREIGN KEY (id_barrio) REFERENCES public.barrio(id_barrio);


--
-- Name: direccion direccion_id_ciudad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_id_ciudad_fkey FOREIGN KEY (id_ciudad) REFERENCES public.ciudad(id_ciudad);


--
-- Name: direccion direccion_id_comuna_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_id_comuna_fkey FOREIGN KEY (id_comuna) REFERENCES public.comuna(id_comuna);


--
-- Name: direccion direccion_id_departamento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_id_departamento_fkey FOREIGN KEY (id_departamento) REFERENCES public.departamento(id_departamento);


--
-- Name: direccion direccion_id_nomenclatura_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_id_nomenclatura_fkey FOREIGN KEY (id_nomenclatura) REFERENCES public.nomenclatura(id_nomenclatura);


--
-- Name: modulo_accion_permitida modulo_accion_permitida_id_accion_permiso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modulo_accion_permitida
    ADD CONSTRAINT modulo_accion_permitida_id_accion_permiso_fkey FOREIGN KEY (id_accion_permiso) REFERENCES public.accion_permiso(id_accion_permiso) ON DELETE CASCADE;


--
-- Name: modulo_accion_permitida modulo_accion_permitida_id_modulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modulo_accion_permitida
    ADD CONSTRAINT modulo_accion_permitida_id_modulo_fkey FOREIGN KEY (id_modulo) REFERENCES public.modulo(id_modulo) ON DELETE CASCADE;


--
-- Name: rol_permiso rol_permiso_id_accion_permiso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT rol_permiso_id_accion_permiso_fkey FOREIGN KEY (id_accion_permiso) REFERENCES public.accion_permiso(id_accion_permiso);


--
-- Name: rol_permiso rol_permiso_id_modulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT rol_permiso_id_modulo_fkey FOREIGN KEY (id_modulo) REFERENCES public.modulo(id_modulo);


--
-- Name: rol_permiso rol_permiso_id_rol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT rol_permiso_id_rol_fkey FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol);


--
-- Name: seguimiento_terreno seguimiento_terreno_id_sitio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT seguimiento_terreno_id_sitio_fkey FOREIGN KEY (id_sitio) REFERENCES public.sitio(id_sitio);


--
-- Name: seguimiento_terreno seguimiento_terreno_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_terreno
    ADD CONSTRAINT seguimiento_terreno_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- Name: seguimiento_zoocriadero seguimiento_zoocriadero_id_tanque_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoocriadero
    ADD CONSTRAINT seguimiento_zoocriadero_id_tanque_fkey FOREIGN KEY (id_tanque) REFERENCES public.tanque(id_tanque);


--
-- Name: seguimiento_zoocriadero seguimiento_zoocriadero_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoocriadero
    ADD CONSTRAINT seguimiento_zoocriadero_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- Name: seguimiento_zoocriadero seguimiento_zoocriadero_id_zoocriadero_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seguimiento_zoocriadero
    ADD CONSTRAINT seguimiento_zoocriadero_id_zoocriadero_fkey FOREIGN KEY (id_zoocriadero) REFERENCES public.zoocriadero(id_zoocriadero);


--
-- Name: sitio sitio_id_direccion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sitio
    ADD CONSTRAINT sitio_id_direccion_fkey FOREIGN KEY (id_direccion) REFERENCES public.direccion(id_direccion);


--
-- Name: tanque tanque_id_tipo_tanque_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tanque
    ADD CONSTRAINT tanque_id_tipo_tanque_fkey FOREIGN KEY (id_tipo_tanque) REFERENCES public.tipo_tanque(id_tipo_tanque);


--
-- Name: tanque tanque_id_zoocriadero_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tanque
    ADD CONSTRAINT tanque_id_zoocriadero_fkey FOREIGN KEY (id_zoocriadero) REFERENCES public.zoocriadero(id_zoocriadero);


--
-- Name: territorio_priorizado territorio_priorizado_id_funcionario_ecosalud_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territorio_priorizado
    ADD CONSTRAINT territorio_priorizado_id_funcionario_ecosalud_fkey FOREIGN KEY (id_funcionario_ecosalud) REFERENCES public.usuario(id_usuario);


--
-- Name: usuario usuario_id_rol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_id_rol_fkey FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol);


--
-- Name: usuario usuario_id_tipodocumento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_id_tipodocumento_fkey FOREIGN KEY (id_tipodocumento) REFERENCES public.tipo_documento(id_tipodocumento);


--
-- Name: zoocriadero zoocriadero_id_persona_cargo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zoocriadero
    ADD CONSTRAINT zoocriadero_id_persona_cargo_fkey FOREIGN KEY (id_persona_cargo) REFERENCES public.usuario(id_usuario);


--
-- Name: copia_seguridad_historial fk_copia_seguridad_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.copia_seguridad_historial
    ADD CONSTRAINT fk_copia_seguridad_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- PostgreSQL database dump complete
--


